spring:
  application:
    name: thymeleaf-web-dev

server:
  port: 8082

#2, \u6570\u636E\u5E93\u914D\u7F6E
thymeleaf-web:
  database:
    username: root
    password: 123456
    url : jdbc:mysql://localhost:3306/thymeleaf?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&allowMultiQueries=true
    driver: com.mysql.jdbc.Driver

  redis:
    host: localhost
    port: 6379
