package com.fisher.arch
import com.fisher.arch.webflux.demo.model.Message
import com.fisher.arch.webflux.demo.model.SceneRule
import com.fisher.arch.webflux.demo.service.DemoService
dialect  "mvel"

rule "Hello World"
    dialect "mvel"
    when
        m : Message(status.equals(Message.HELLO), message : message)
        $scene: SceneRule(message == m)
    then
        System.out.println( message);
    modify ( m ) { message = "Goodbye cruel world",status = Message.GOODBYE };
end

rule "Good Bye"
    dialect "java"
    when
       Message( status == Message.GOODBYE, message : message )
    then
        System.out.println( message );
end