logging:
  path: ./logs
  config: classpath:logback-spring.xml

spring:
  profiles:
    active: @build.profile.id@
  thymeleaf:
    prefix: classpath:/templates/
    enabled: true
    mode: HTML
    suffix: .html
    encoding: UTF-8
    cache: false

### dev
---
spring:
  redis:
    host: localhost
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: 1ms
        max-idle: 7
        min-idle: 2
  profiles: dev
server:
    port: 9091
multidatasource:
  - db1:
      username: root
      password: 123456
      url:
  - db2:
      username: root
      password: 123456
      url:
        -
  - db3:


### uat
---
spring:
  redis:
    host: localhost
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: 1ms
        max-idle: 7
        min-idle: 2
  profiles: uat
server:
  port: 9092

### prod
---
spring:
  redis:
    host: localhost
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: 1ms
        max-idle: 7
        min-idle: 2
  profiles: prod
server:
  port: 9093
