logging:
  path: ./logs

spring:
  profiles:
    active: @build.profile.id@

### \u5F00\u53D1\u73AF\u5883
---
spring:
  profiles: dev
server:
    port: 9091

### uat\u73AF\u5883
---
spring:
  profiles: uat
server:
  port: 9092

### \u751F\u4EA7\u73AF\u5883
---
spring:
  profiles: prod
server:
  port: 9093
