#1, \u9879\u76EE\u57FA\u672C\u914D\u7F6E

spring:
  application:
    name: thymeleaf-web-dmeo

  profiles:
    active: @build.profile.id@
  boot:
    admin:
      client:
        url: http://localhost:8081
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
thymeleaf:
  app:
    name: shefenfei
    author: shefenfei
    default-subject: hahah
    casttime: 100s
    server-list:
      - server1
      - server2
    enable: false
    test: aaa
