spring:
  application:
    name: thymeleaf-web-prod

server:
  port: 8082

#2, \u6570\u636E\u5E93\u914D\u7F6E
thymeleaf-web:
  database:
    username: @datasource.username@
    password: @datasource.password@
    url : @datasource.url@
    driver: @datasource.driver@

  redis:
    host: localhost
    port: 6379
