server:
  port: 9999
spring:
  application:
    name: only-school-c
  security:
    user:
      name: root
      password: 123456
  cloud:
    gateway:
      routes:
        - id: prepath-route
          uri: http://localhost:9999
          predicates:
            - Path=/school/**
          filters:
            - StripPrefix=1
        - id: eas-route
          uri: http://10.10.10.41:10000/crm-backend
          predicates:
            - Path=/demo/**
          filters:
            - PrefixPath=/crm-backend
logging:
  level:
    root: debug
